POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

###

POST http://localhost:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "kerfuffle my sharbert and fornax me"
}

###

POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "hello@chirpy.com",
  "password": "1234"
}

###

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "hello@chirpy.com",
  "password": "1234"
}

###


POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
  "email": "hello@chirpy.com",
  "password": "5678"
}

###

POST http://localhost:8080/admin/reset HTTP/1.1

###

GET http://localhost:8080/admin/metrics HTTP/1.1

###

POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI3YTMwYjExZS02NGNkLTQwZmItYWE4Yy0zNWQzNTU2ZGMxMzgiLCJpYXQiOjE3NzI3OTA4MDIsImV4cCI6MTc3Mjc5NjgwMn0.BGH1RaYpvQ1Ts1Je7xFNb5aB4FPStFnVrVMbBpOYDZ4

{
  "body": "I'm always kind!",
  "userId": "7a30b11e-64cd-40fb-aa8c-35d3556dc138"
}

###

GET http://localhost:8080/api/chirps HTTP/1.1

###

GET http://localhost:8080/api/chirps/e2a1b8dd-ae48-4010-a912-c00386104aa0 HTTP/1.1